# -*- coding: utf-8 -*-
"""STM_Study01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B1BWjY_Wv7pzTf0qI0qvinCkIy7QVnew
"""

3+5   #運算顯示方式說明
3-5
3*5
3**5

print(3+5)   #運算全部顯示方式說明
print(3-5)
print(3*5)
print(3**5)

print(100)   #int,str,bool,Flag
print(3.1415)
print(1+2j)
print(True)
print(False)
print('Hello Word')
print("http://www.google.com")

x=3+5   #計算測試
x=x+1
print(x)

"""x = 2   #不知道按到什麼才變這意
y = 3
z = "Hello Word"
x = 9
print(x)
"""

x = 2   #計算結果顯示（以最後值為最終結果）
y = 3
z = "Hello Word"
x = 9
print(x)

# x123 = "Hello Word"   #錯誤語法及ctrl+/快速上註解符號＃
# _xX_123_ = "Hello Word"
# 123_xX_ = "Hello Word"
# !@#$%^&*()- = "Hello Word"

print(5//3)  #除數_除法取整數
print(5/3)   #除數_除法取小數點
print(9%2)   #餘數_除法取餘數
print(9%3)   #餘數_除法取餘數
print(9%4)   #餘數_除法取餘數
print(9%5)   #餘數_除法取餘數
print(9%6)   #餘數_除法取餘數
print(9%7)   #餘數_除法取餘數
print(9%8)   #餘數_除法取餘數
print(9%9)   #餘數_除法取餘數

name = input('請輸入你的名字')   #輸入,輸出說明
print('您好,',name)

print(4 == 3)   #關係運算實例
print(4 != 3)
print(4 >= 3)

# 輸入一個整數,請判斷奇偶

num = 100

if num % 2 == 0:
    print(num, '為偶數')
else:
    print(num, '為基數')

# 輸入一個整數,請判斷奇偶(str類型會發生異常)

num = input('請輸入一個整數')   #input輸入任何資料都是String

if num % 2 == 0:
    print(num, '為偶數')
else:
    print(num, '為基數')

# 輸入一個整數,請判斷奇偶(str類型會發生異常)

# num = input('請輸入一個整數')   #input輸入任何資料都是String

# num = int(num)   #int轉換num為數值或用下列方式可簡化編寫長度

num = int(input('請輸入一個整數'))

if num % 2 == 0:
    print(num, '為偶數')
else:
    print(num, '為基數')

# 練習題：輸入一個0到100之間的分數score,請根據以下規則輸出對應的等級：(語法一)

score = int(input('請輸入分數'))
if 0 <=  score <= 100 :
  if 90 <= score <= 100:
    print("A")
  elif 80 <= score < 90 :
    print("B")
  elif 70 <= score < 80 :
    print("C")
  elif 60 <= score < 70 :
    print("D")
  else:
    print("F")
else:
    print("Invalid Score")

# 練習題：輸入一個0到100之間的分數score,請根據以下規則輸出對應的等級：(語法二)
score = int(input('請輸入分數: '))

if score < 0 or score > 100:
    print("Invalid Score")
elif score >= 90:
    print("A")
elif score >= 80:
    print("B")
elif score >= 70:
    print("C")
elif score >= 60:
    print("D")
else:
    print("F")

# 練習題：輸入一個0到100之間的分數score,請根據以下規則輸出對應的等級：(老師說明範例)
# Ture and False
# True or False
# not True

x = 101
if x >= 90 and x <= 100:
  print("A")
elif 80 <= x <90:
  print("B")
elif 70 <= x <80:
  print("C")
elif 60 <= x <70:
  print("D")
elif 0 <= x <60:
  print("F")
else:
    print("輸入的成績無效")

num = '3.1415'
float(nim)

int('100')      #轉成int
float('3.1415')      #轉成float
str(100)      #轉成str
bool(0)
bool(2)

#編寫程式,物件類型很重要
#字串
x = '''How are you
I'm fine.
How about you?
'''

print(x)

#字串相加效果

'user/deaktop' + '/' + 'test.txt'

#字串相乘效果
'**' * 10

#字串轉義效果(轉義,逃脫)
#'I'm fine.' #字串因符號關係而出現錯誤,故需留意排列方式
# 'I\'m fine.' #字串因符號加上\符號則可正常print
# "I'm fine."  #字串因符號改用""符號,可正常print

# s = "How are you?\nI'm fine."
# print(s)

#s ='C:\\user\\desktop\\number.txt'#字串符號\改用\\符號,可正常print
s = r'C:\user\desktop\number.txt'#字串符號r',可正常print
print(s)

# a, b, c, d, e, f = "python" # unpack (注意,左右文字數量要相等)

# print(a,c,f)

# a, *b, c= "python" # unpack (注意,左右文字數量要相等) print結果p ['y', 't', 'h', 'o'] n

# print(a,b,c)

a, b, *c= "python" # unpack (注意,左右文字數量要相等) print結果p y ['t', 'h', 'o', 'n']

print(a,b,c)

l = [100, 3.1415, 'Hello', True]  # 四個對四個
a, b, c, d = l

t = ('Hello', 'Word', 'python')  # 三個對三個
x, y, z, = t
print(a)

#讀取單一字元
# "A B C D E" 左到右 , 1, 2, 3, 4, 5 左到右  -5, -4, -3, -2, -1 右到左

word = "python"
word[-1]

l = [100, 3.1415, 'Hello', True]
l[-2]